# Generated by Django 3.2.4 on 2021-06-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
