# Generated by Django 3.2.4 on 2021-07-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0004_auto_20210704_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='location',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
