# Generated by Django 3.1 on 2021-07-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0007_auto_20210716_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
