# Generated by Django 3.1 on 2021-08-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0008_auto_20210729_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='revenue',
            field=models.IntegerField(default=0),
        ),
    ]
