# Generated by Django 3.2.6 on 2021-09-01 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0011_auto_20210829_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='email',
        ),
    ]
