# Generated by Django 3.2.7 on 2021-09-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0012_remove_userdetail_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='api_key',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='userrole',
            name='api_key',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
