# Generated by Django 3.2.7 on 2021-09-20 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0013_auto_20210907_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='api_key',
        ),
    ]
