# Generated by Django 3.2.4 on 2021-06-25 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=250)),
                ('case_manager_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_manager', to='auth1.userdetail')),
                ('client_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case', to='auth1.userdetail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('price', models.IntegerField()),
                ('status', models.CharField(max_length=250)),
                ('comment', models.CharField(max_length=250)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='project.case')),
                ('recipient_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_user', to='auth1.userdetail')),
                ('submit_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_sumbit_user', to='auth1.userdetail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='project.case')),
                ('submit_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='auth1.userdetail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('price', models.IntegerField()),
                ('status', models.CharField(max_length=250)),
                ('comment', models.CharField(max_length=250)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_invoice', to='project.case')),
                ('recipient_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='auth1.userdetail')),
                ('submit_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_submit_user', to='auth1.userdetail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='project.invoice')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='project.message')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='project.quote')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
