# Generated by Django 3.2.4 on 2021-07-19 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20210716_2028'),
        ('project', '0005_auto_20210716_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='survey.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.productcategory'),
        ),
    ]
