# Generated by Django 3.1 on 2021-08-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20210812_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='title',
            field=models.CharField(default='quotetitle', max_length=250),
            preserve_default=False,
        ),
    ]
