# Generated by Django 3.2.7 on 2021-09-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20210828_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='api_key',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='case',
            name='api_key',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='invoice',
            name='api_key',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='message',
            name='api_key',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='quote',
            name='api_key',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
