# Generated by Django 3.2.7 on 2021-09-20 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20210907_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='case',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='message',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='api_key',
        ),
    ]
