# Generated by Django 3.2.4 on 2021-07-13 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20210708_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='response',
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=250)),
                ('response', models.CharField(max_length=250)),
                ('survey_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='survey.surveyresponse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
