# Generated by Django 3.2.7 on 2021-09-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_auto_20210828_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='api_key',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='api_key',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='response',
            name='api_key',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='survey',
            name='api_key',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='api_key',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
