# Generated by Django 3.2.7 on 2021-09-20 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_auto_20210907_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='response',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='api_key',
        ),
    ]
