# Generated by Django 3.2.4 on 2021-07-04 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_comment_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='status',
            new_name='status_comment',
        ),
    ]
