# Generated by Django 3.2.4 on 2021-07-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20210704_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentmeta',
            name='post',
        ),
        migrations.AddField(
            model_name='content',
            name='category',
            field=models.CharField(choices=[('MW', 'Modern Workplace'), ('CP', 'Customer Portal'), ('BI', 'BI Report'), ('BC', 'Business Consulting')], default=1, max_length=2, verbose_name='category'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PostCategory',
        ),
    ]
