# Generated by Django 3.2.4 on 2021-07-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20210708_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='status',
            field=models.CharField(choices=[('F', 'Featured'), ('O', 'Ordinary')], max_length=1, verbose_name='status'),
        ),
    ]
