# Generated by Django 3.2.4 on 2021-07-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='category',
            field=models.CharField(choices=[('MW', 'Modern Workplace'), ('CP', 'Customer Portal'), ('BI', 'BI Report'), ('BC', 'Business Consulting')], max_length=2, null=True, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='content',
            name='url',
            field=models.CharField(max_length=250),
        ),
    ]
