# Generated by Django 3.1 on 2021-07-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20210715_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='image_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
