# Generated by Django 3.2.7 on 2021-09-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_auto_20210828_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='api_key',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='content',
            name='api_key',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='contentmeta',
            name='api_key',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
