# Generated by Django 3.2.7 on 2021-09-20 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_auto_20210907_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='content',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='contentmeta',
            name='api_key',
        ),
    ]
